'use client';
import { useEffect, useState, type ReactNode } from 'react';
import { dailyModel, hitterTrend, rate } from './daily-report-model';
const fmt=(v:number)=>v.toFixed(1);
const stamp=(v:string)=>new Date(v).toLocaleString('en-US',{timeZone:'America/Phoenix',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+' AZ';
function Signal({direction}:{direction:string|null}){return direction?<span className={'signal '+direction}>{direction==='up'?'↑ Rising':direction==='down'?'↓ Falling':'→ Steady'}</span>:null;}
function Player({p}:{p:any}){const status=typeof p.rosterStatus==='string'&&!/unknown|unavailable|unverified|\?|^\s*$/i.test(p.rosterStatus)?p.rosterStatus:null;return <span className="player">{p.name}{status&&<small>{status}</small>}</span>;}
function Board({label,headers,rows}:{label:string;headers:string[];rows:ReactNode[][]}){return rows.length?<div className="board" role="region" aria-label={label} tabIndex={0}><table><caption className="sr-only">{label}</caption><thead><tr>{headers.map(h=><th key={h} scope="col" data-column={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>:null;}
export default function DailyReport({current,failed=false}:{current:any;failed?:boolean}){
 const [,setNow]=useState(0);useEffect(()=>{const timer=setInterval(()=>setNow(n=>n+1),30000);return()=>clearInterval(timer);},[]);
 const d=failed?null:dailyModel(current);
 if(!d)return <p role="status" className="load-status">{current||failed?'Refresh to load current evidence.':'Loading today’s data…'}</p>;
 const hitters=d.hitters.filter((p:any)=>[p.seven,p.fourteen,p.thirty].some(w=>rate(w)!==null));
 const pitchers=d.pitchers.filter((p:any)=>p.recent.average!==null);
 const opposing=d.hitterRows.some((p:any)=>p.opposingPitcher),handedness=d.hitterRows.some((p:any)=>p.opposingPitcherHand),matchup=d.hitterRows.some((p:any)=>p.matchup),trend=d.hitterRows.some((p:any)=>p.trendDirection);
 const windows=['seven','fourteen','thirty'].filter(k=>hitters.some((p:any)=>rate(p[k])!==null));
 const hitterArrows=hitters.some((p:any)=>hitterTrend(p)),pitcherArrows=pitchers.some((p:any)=>p.recent.trend);
 const actions=d.hitters.filter((p:any)=>hitterTrend(p)==='down');
 return <article><div className="freshness"><strong>{d.today}</strong><span>Updated {stamp(current.generatedAt)}</span><span>Fantrax {stamp(current.feed.generatedAt)}</span></div>
 <section><h2><span>01</span>Today’s Actions</h2>{actions.length>0?<div className="actions">{actions.map((p:any)=><div className="action" key={p.name}><span className="watch">WATCH · HITTER</span><Player p={p}/><p>{fmt(rate(p.seven)!)} FP/game · 7D <span>vs {fmt(rate(p.thirty)!)} · 30D</span></p></div>)}</div>:<p className="quiet">No declining hitter trend flags today.</p>}</section>
 <section><h2><span>02</span>Hitters — Today’s Matchups</h2><Board label="Today’s hitter matchups" headers={['Player','Opponent',...(opposing?['Opposing SP']:[]),...(handedness?['Hand']:[]),...(matchup?['Matchup rating']:[]),...(trend?['Trend']:[])]} rows={d.hitterRows.map((p:any)=>[<Player p={p}/>,p.opponent,...(opposing?[p.opposingPitcher]:[]),...(handedness?[p.opposingPitcherHand]:[]),...(matchup?[p.matchup&&<span className={'rating '+p.matchup.toLowerCase()}>{p.matchup}</span>]:[]),...(trend?[<Signal direction={p.trendDirection}/>]:[])])}/>{current.scheduleVerified&&!d.hitterRows.length&&<p className="quiet">No hitter games scheduled today.</p>}</section>
 <section><h2><span>03</span>Hitters — 7 / 14 / 30 Day Trends <small>Longball FP/game · through {current.yesterday}</small></h2><Board label="Hitter trends" headers={['Player',...windows.map(k=>({seven:'7D',fourteen:'14D',thirty:'30D'}[k]!)),...(hitterArrows?['Trend']:[])]} rows={hitters.map((p:any)=>[<Player p={p}/>,...windows.map(k=>rate(p[k])===null?null:fmt(rate(p[k])!)),...(hitterArrows?[<Signal direction={hitterTrend(p)}/>]:[])])}/></section>
 <section><h2><span>04</span>Pitchers — Today’s Starts</h2><Board label="Today’s pitcher starts" headers={['Player','Opponent']} rows={d.starts.map((s:any)=>[<Player p={s.player}/>,s.opponent])}/>{current.scheduleVerified&&!d.starts.length&&<p className="quiet">No Desert Rats probable starters listed today.</p>}</section>
 <section><h2><span>05</span>Pitchers — Recent Performance / Trend <small>Last 3 starts · Longball FP/start</small></h2><Board label="Pitcher recent performance" headers={['Player','FP/start',...(pitcherArrows?['Trend']:[])]} rows={pitchers.map((p:any)=>[<Player p={p}/>,fmt(p.recent.average),...(pitcherArrows?[<Signal direction={p.recent.trend}/>]:[])])}/></section>
 {(d.reserveHitters.length > 0 || d.reservePitchers.length > 0) && <section aria-label="Reserve"><h2><span>06</span>Reserve</h2>{d.reserveHitters.length > 0 && <><h3 className="ir-label">Hitters</h3><Board label="Reserve hitters" headers={['Player', 'Current status']} rows={d.reserveHitters.map((p:any)=>[p.name, 'Reserve · Fantrax'])}/></>}{d.reservePitchers.length > 0 && <><h3 className="ir-label">Pitchers</h3><Board label="Reserve pitchers" headers={['Player', 'Current status']} rows={d.reservePitchers.map((p:any)=>[p.name, 'Reserve · Fantrax'])}/></>}</section>}
 {(d.injuredHitters.length > 0 || d.injuredPitchers.length > 0) && <section aria-label="Injured Reserve"><h2><span>{d.reserveHitters.length > 0 || d.reservePitchers.length > 0 ? '07' : '06'}</span>Injured Reserve</h2>{d.injuredHitters.length > 0 && <><h3 className="ir-label">Hitters</h3><Board label="Injured reserve hitters" headers={['Player', 'Current status']} rows={d.injuredHitters.map((p:any)=>[p.name, 'Injured reserve · Fantrax'])}/></>}{d.injuredPitchers.length > 0 && <><h3 className="ir-label">Pitchers</h3><Board label="Injured reserve pitchers" headers={['Player', 'Current status']} rows={d.injuredPitchers.map((p:any)=>[p.name, 'Injured reserve · Fantrax'])}/></>}</section>}
 </article>;
}
