// Saved League Setup is the scoring authority. MLB BB includes IBB; do not double count it.
export const GS_CAP = 12;
export const MODEL = 'Longball · saved League Setup · v1';
export type Stat = Record<string, any>;
const n=(s:Stat,k:string)=>Number(s[k]??0);
export function inningsOuts(ip:unknown) { const [whole,part='0']=String(ip??'0').split('.');if(!/^[0-2]$/.test(part)||!/^\d+$/.test(whole))throw Error('Invalid baseball innings');return Number(whole)*3+Number(part); }
export function hittingPoints(s:Stat, game=false) { const singles=n(s,'hits')-n(s,'doubles')-n(s,'triples')-n(s,'homeRuns');const cycle=game&&singles>0&&n(s,'doubles')>0&&n(s,'triples')>0&&n(s,'homeRuns')>0;return singles*1.5+n(s,'doubles')*3+n(s,'triples')*3+n(s,'homeRuns')*4+n(s,'runs')+n(s,'rbi')*2+n(s,'baseOnBalls')+n(s,'hitByPitch')+n(s,'stolenBases')*3-n(s,'caughtStealing')-n(s,'strikeOuts')-n(s,'groundIntoDoublePlay')*2+n(s,'sacBunts')+n(s,'sacFlies')+(cycle?5:0); }
export function pitchingPoints(s:Stat) { const outs=inningsOuts(s.inningsPitched);const qs=n(s,'gamesStarted')>0&&outs>=18&&n(s,'earnedRuns')<=3;const noHitter=n(s,'completeGames')>0&&n(s,'hits')===0&&outs>=27;return outs*2/3+n(s,'strikeOuts')*1.5+n(s,'wins')*5-n(s,'losses')*5-n(s,'earnedRuns')*2-n(s,'hits')*.5-n(s,'baseOnBalls')*.5-n(s,'homeRuns')*2+(qs?5:0)+(n(s,'saves')+n(s,'holds'))*5-n(s,'blownSaves')*3+n(s,'completeGames')*2+n(s,'shutouts')*2+(noHitter?5:0); }
export function dates(now=new Date()) {const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Phoenix',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);const d=new Date(today+'T12:00:00Z');const day=d.getUTCDay();const shift=(base:string,days:number)=>{const x=new Date(base+'T12:00:00Z');x.setUTCDate(x.getUTCDate()+days);return x.toISOString().slice(0,10);};const monday=shift(today,-((day+6)%7));return {today,yesterday:shift(today,-1),monday,sunday:shift(monday,6),nextMonday:shift(monday,7),start30:shift(today,-30),shift,day};}
export function pitcherQuality(points:number|null) {return points===null?'Not rated':points>=25?'Strong':points>=15?'Average':points>=0?'Vulnerable':'High risk';}
export function trend(current:Stat, previous:Stat, pitcher:boolean) {if(current.samples<(pitcher?2:4)||previous.samples<(pitcher?2:4))return {label:'Not enough evidence',why:'Insufficient comparable playing time in the two seven-day windows.'};const a=current.points/current.samples,b=previous.points/previous.samples;const skill=pitcher?current.kbb-previous.kbb:(current.bb-current.k)-(previous.bb-previous.k);const rate=(a-b)/Math.max(5,Math.abs(b));const up=rate>.15&&skill>1,down=rate<-.15&&skill< -1;return {label:up?'Trending Up':down?'Trending Down':'Stable',why:`Longball points per ${pitcher?'appearance':'game'} ${a.toFixed(1)} vs ${b.toFixed(1)}; ${pitcher?'K−BB%':'BB% minus K%'} change ${skill.toFixed(1)} pp. ${!up&&!down?'Production and skill signals do not jointly confirm a directional move.':''}`};}
