import {readSnapshot} from './fantrax';
import {publishedCandidates} from './shared-snapshot.mjs';
import {dates,GS_CAP,MODEL,hittingPoints,pitchingPoints,pitcherQuality,trend} from './longball';
import type {Stat} from './longball';
const BASE='https://statsapi.mlb.com/api/v1';
export const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
async function get(path:string) {const r=await fetch(BASE+path,{signal:AbortSignal.timeout(18000)});if(!r.ok)throw Error('MLB feed unavailable');return r.json() as Promise<any>;}
async function mapLimit<T,R>(items:T[],fn:(v:T)=>Promise<R>,limit=6){const out:R[]=new Array(items.length);let i=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(i<items.length){const idx=i++;out[idx]=await fn(items[idx]);}}));return out;}
export async function playerEvidence(person:any,now=new Date(),role?:'pitching'|'hitting') {
 const d=dates(now),pitcher=role?role==='pitching':person.primaryPosition?.type==='Pitcher',group=pitcher?'pitching':'hitting';
 try {const data=await get(`/people/${person.id}/stats?stats=gameLog&group=${group}&season=${d.today.slice(0,4)}&startDate=${d.start30}&endDate=${d.yesterday}`);const block=data.stats?.find((s:any)=>s.group?.displayName===group);if(!block)throw Error();const logs=(block.splits??[]).filter((l:any)=>l.date>=d.start30&&l.date<=d.yesterday);
 const summarize=(start:string,end:string)=>{const rows=logs.filter((r:any)=>r.date>=start&&r.date<=end);const sum=(k:string)=>rows.reduce((a:number,r:any)=>a+Number(r.stat[k]??0),0);const denom=sum(pitcher?'battersFaced':'plateAppearances');return {points:rows.reduce((a:number,r:any)=>a+(pitcher?pitchingPoints(r.stat):hittingPoints(r.stat,true)),0),samples:rows.length,starts:sum('gamesStarted'),pa:denom,k:denom?sum('strikeOuts')/denom*100:0,bb:denom?sum('baseOnBalls')/denom*100:0,kbb:denom?(sum('strikeOuts')-sum('baseOnBalls'))/denom*100:0,outs:pitcher?rows.reduce((a:number,r:any)=>a+Number(String(r.stat.inningsPitched??0).split('.')[0])*3+Number(String(r.stat.inningsPitched??0).split('.')[1]??0),0):0};};
 const seven=summarize(d.shift(d.today,-7),d.yesterday),prior=summarize(d.shift(d.today,-14),d.shift(d.today,-8)),fourteen=summarize(d.shift(d.today,-14),d.yesterday),thirty=summarize(d.start30,d.yesterday),yesterday=summarize(d.yesterday,d.yesterday);
 const starts=logs.filter((r:any)=>Number(r.stat.gamesStarted)>0);const base=pitcher?(starts.length>=3?starts.reduce((a:number,r:any)=>a+pitchingPoints(r.stat),0)/starts.length:null):(thirty.samples>=10?thirty.points/thirty.samples:null);
 return {id:person.id,name:person.fullName,team:person.currentTeam?.id,teamName:person.currentTeam?.name,position:person.primaryPosition?.abbreviation,pitcher,active:person.active!==false,seven,fourteen,thirty,yesterday,base,quality:pitcher?pitcherQuality(base):null,trend:trend(seven,prior,pitcher),logs,coverage:'MLB game logs · through yesterday',advanced:null};
 }catch{return {id:person.id,name:person.fullName,team:person.currentTeam?.id,teamName:person.currentTeam?.name,position:person.primaryPosition?.abbreviation,pitcher,active:person.active!==false,base:null,quality:'Not rated',coverage:'MLB statistics unavailable',trend:{label:'Not enough evidence',why:'Game logs could not be verified.'},logs:[]};}
}
export async function buildOffice(now=new Date(),packet:any=null,feed=undefined as Awaited<ReturnType<typeof readSnapshot>>|undefined) {
 const d=dates(now);feed??=await readSnapshot();const team=feed.snapshot?.teams.find(t=>/desert rats/i.test(t.Team));
 const roster=feed.snapshot?.players.filter(p=>p['Fantasy Team ID']===team?.['Team ID'])??[];
 const [poolResult,scheduleResult]=await Promise.allSettled([get(`/sports/1/players?season=${d.today.slice(0,4)}&hydrate=currentTeam`),get(`/schedule?sportId=1&startDate=${d.monday}&endDate=${d.sunday}&hydrate=probablePitcher,team`)]);
 const people=poolResult.status==='fulfilled'?poolResult.value.people??[]:[];const games=scheduleResult.status==='fulfilled'?(scheduleResult.value.dates??[]).flatMap((v:any)=>v.games.map((g:any)=>({...g,date:v.date}))):[];
 const freshPacket=packet&&Date.now()-Date.parse(packet.capturedAt)<=24*3600000?packet:null;
 const freeAgents=publishedCandidates(feed.snapshot,freshPacket?.freeAgents??[]);
 const matchup=freshPacket?.matchup?.week===d.monday?freshPacket.matchup:null;
 const opponentRoster=matchup?feed.snapshot?.players.filter(p=>p['Fantasy Team ID']===matchup.opponentTeamId)??[]:[];
 const matched=roster.map(p=>({source:p,person:people.find((v:any)=>normalize(v.fullName)===normalize(p.Player??''))}));
 const extras=[...opponentRoster.map(p=>p.Player),...freeAgents.map((p:any)=>p.name)].map(name=>people.find((v:any)=>normalize(v.fullName)===normalize(name??''))).filter(Boolean);
 const probable=games.flatMap((g:any)=>['away','home'].map(side=>{const other=side==='away'?'home':'away';return {id:g.teams[side].probablePitcher?.id,name:g.teams[side].probablePitcher?.fullName??'TBD',team:g.teams[side].team.id,opponent:g.teams[other].team.name,opponentId:g.teams[other].team.id,date:g.date,gameId:g.gamePk,status:g.status?.detailedState};}));
 const ids=new Set([...matched.filter(v=>v.person).map(v=>v.person.id),...extras.map(p=>p.id),...(roster.length?probable.filter((p:any)=>p.id).map((p:any)=>p.id):[])]);
 const evidence=await mapLimit([...ids] as number[],async id=>{let person=people.find((p:any)=>p.id===id);if(!person){try{person=(await get(`/people/${id}?hydrate=currentTeam`)).people?.[0];}catch{}}return person?playerEvidence(person,now):null;});
 const ev=new Map(evidence.filter(Boolean).map((p:any)=>[p.id,p]));
 const pitchEv=new Map(ev);
 const twoWay=matched.filter(({source,person})=>person&&/\b(SP|RP|P)\b/.test(source.Positions??'')&&!ev.get(person.id)?.pitcher);
 const dualIds=[...new Set([...twoWay.map(v=>v.person.id),...probable.filter((p:any)=>p.id&&ev.has(p.id)&&!ev.get(p.id)?.pitcher).map((p:any)=>p.id)])];
 for(const id of dualIds){const person=people.find((p:any)=>p.id===id);if(person)pitchEv.set(id,await playerEvidence(person,now,'pitching'));}
 const players=matched.flatMap(({source,person})=>{const base={...ev.get(person?.id),name:source.Player||'Name unavailable',fantraxId:source['Player ID'],rosterStatus:source.Status??'Unknown',positions:source.Positions??'Unknown',matched:!!person,pitcher:ev.get(person?.id)?.pitcher??/\b(SP|RP|P)\b/.test(source.Positions??''),trend:ev.get(person?.id)?.trend??{label:'Not enough evidence',why:'Fantrax player could not be matched to an MLB ID.'}};return twoWay.some(v=>v.source===source)?[base,{...base,...pitchEv.get(person.id),name:base.name+' (pitching)',fantraxId:base.fantraxId+':pitching',positions:'SP',rosterStatus:base.rosterStatus}]:[base];});
 const starts=probable.filter((p:any)=>players.some(v=>v.id===p.id&&v.pitcher)).map((p:any)=>{const e=pitchEv.get(p.id);return {...p,quality:e?.quality??'Not rated',projection:e?.base??null,matchup:'Opponent adjustment unavailable',recommendation:e?.base==null?'Hold for evidence':e.base>=15?'Start candidate':'Sit candidate',why:e?.base==null?'At least three recent starts are needed.':`${e.base.toFixed(1)} Longball points per start over the last 30 days. Confirm active status, opponent quality and remaining GS budget.`};});
 const hitterOutlook=players.filter(p=>!p.pitcher).map(p=>{const slate=games.filter((g:any)=>g.teams.away.team.id===p.team||g.teams.home.team.id===p.team).map((g:any)=>{const opp=g.teams.home.team.id===p.team?g.teams.away:g.teams.home;const pitcherId=opp.probablePitcher?.id;const rating=pitchEv.get(pitcherId);const hand=people.find((v:any)=>v.id===pitcherId)?.pitchHand?.code;return {date:g.date,opponent:opp.team.name,pitcher:opp.probablePitcher?.fullName??'TBD',pitcherHand:hand==='L'?'LHP':hand==='R'?'RHP':null,quality:rating?.quality??'Not rated',base:rating?.base??null};});const rated=slate.filter((g:any)=>g.base!==null);const mean=rated.length?rated.reduce((a:number,g:any)=>a+g.base,0)/rated.length:null;return {name:p.name,slate,grade:rated.length!==slate.length||!slate.length?'Incomplete':mean!>=25?'C · Difficult':mean!>=15?'B · Balanced':'A · Favorable',projection:p.base!=null&&slate.length>0?p.base*slate.length:null};});
 const opponentIds=new Set(opponentRoster.map(p=>people.find((v:any)=>normalize(v.fullName)===normalize(p.Player??''))?.id).filter(Boolean));
 const opponentStarts=probable.filter((p:any)=>opponentIds.has(p.id)).map((p:any)=>({...p,quality:pitchEv.get(p.id)?.quality??'Not rated',projection:pitchEv.get(p.id)?.base??null,matchup:'Opponent adjustment unavailable',recommendation:'Opponent start',why:'Probable schedule; Longball 30-day rate.'}));
 const futureGames=(id:number)=>games.filter((g:any)=>g.date>=d.today&&(g.teams.away.team.id===id||g.teams.home.team.id===id)).length;
 const futureStarts=(id:number)=>probable.filter((s:any)=>s.id===id&&s.date>=d.today).length;
 const projected=(p:any)=>p.base==null?null:p.base*(p.pitcher?futureStarts(p.id):futureGames(p.team));
 const market=freeAgents.map((fa:any)=>{const person=people.find((p:any)=>normalize(p.fullName)===normalize(fa.name));const p=ev.get(person?.id);const eligible=players.filter(v=>v.pitcher===p?.pitcher&&v.base!=null&&!/\b(IR|IL)\b/i.test(v.rosterStatus)&&fa.positions.split(/[,/ ]+/).some((pos:string)=>v.positions.split(/[,/ ]+/).includes(pos))).sort((a,b)=>(projected(a)??0)-(projected(b)??0));const replacement=eligible[0];const gain=p&&replacement&&projected(p)!=null?projected(p)!-projected(replacement)!:null;const category=!p?.pitcher?'Hitters':p.base==null?'Traps':p.trend.label==='Trending Up'?'Breakouts':p.trend.label==='Trending Down'||p.base<0?'Traps':p.base>=20?'Multi-week Adds':'Streamers';return {...fa,...p,name:fa.name,category,replacement:replacement?.name??null,gain,projection:p?projected(p):null,recommendation:gain!=null&&gain>0?'ADD candidate / review DROP':'HOLD',why:gain==null?'Matching eligibility, workload or recent production is incomplete.':`${gain.toFixed(1)} estimated Longball points versus ${replacement.name} over the remaining week. Confirm health, lineup and GS budget.`,coverage:'Fantrax availability; MLB Longball rates. Advanced-source corroboration unavailable.'};});
 return {model:MODEL,generatedAt:now.toISOString(),today:d.today,yesterday:d.yesterday,week:d.monday,weekEnd:d.sunday,nextMonday:d.nextMonday,cap:GS_CAP,feed:{status:feed.status,message:feed.message,generatedAt:feed.snapshot?.generated_at??null},roster:players,starts,hitterOutlook,projectedStarts:starts.length,unconfirmedPitchers:players.filter(p=>p.pitcher&&!starts.some((s:any)=>s.id===p.id)).map(p=>p.name),scheduleVerified:scheduleResult.status==='fulfilled',poolVerified:poolResult.status==='fulfilled',matchup,market,opponentStarts,marketVerified:feed.status==='current'&&!!freshPacket?.freeAgents,opponentRoster,matchupCapturedAt:freshPacket?.capturedAt??null,sources:{Fantrax:feed.status,MLB:scheduleResult.status==='fulfilled'?'Schedule and recent game logs':'Unavailable',Statcast:'Not connected',FanGraphs:'Not connected','Pitcher List':'Not connected'},limitations:['Fantrax evidence expires after 24 hours.','MLB points include bench production; they are not credited Fantrax team totals.','Estimates use trailing 30-day Longball rates; no opponent, Statcast or playing-time adjustment is available.','Two-way players require separate verified hitting and pitching identities.']};
}
export function changesSince(baseline:any,current:any){if(!baseline)return [];const changes:any[]=[];const old=baseline.starts??[],now=current.starts??[];for(const start of old){const next=now.find((s:any)=>s.id===start.id&&s.gameId===start.gameId);if(!next)changes.push({name:start.name,why:`Monday: ${start.date} vs ${start.opponent}. This probable start is no longer listed; verify scratch or rotation movement.`});else if(next.date!==start.date||next.opponent!==start.opponent||next.status!==start.status&&/postpon|cancel/i.test(next.status??''))changes.push({name:start.name,why:`${start.date} vs ${start.opponent} → ${next.date} vs ${next.opponent} (${next.status}).`});}for(const start of now)if(!old.some((s:any)=>s.id===start.id&&s.gameId===start.gameId))changes.push({name:start.name,why:`New projected start: ${start.date} vs ${start.opponent}.`});for(const p of current.roster??[]){const before=baseline.roster?.find((v:any)=>v.fantraxId===p.fantraxId);if(!before)changes.push({name:p.name,why:'Added to the published Desert Rats roster since Monday.'});else if(before.rosterStatus!==p.rosterStatus||before.active!==p.active)changes.push({name:p.name,why:`Status changed: ${before.rosterStatus} → ${p.rosterStatus}. MLB active: ${String(before.active)} → ${String(p.active)}.`});}for(const p of baseline.roster??[])if(!current.roster.some((v:any)=>v.fantraxId===p.fantraxId))changes.push({name:p.name,why:'No longer on the published Desert Rats roster.'});for(const hitter of current.hitterOutlook??[]){const before=baseline.hitterOutlook?.find((h:any)=>h.name===hitter.name);for(const game of hitter.slate??[]){const original=before?.slate?.find((g:any)=>g.date===game.date&&g.opponent===game.opponent);if(original&&original.pitcher!==game.pitcher)changes.push({name:hitter.name,why:`${game.date}: opposing starter ${original.pitcher} → ${game.pitcher}.`});}}if(baseline.projectedStarts!==current.projectedStarts)changes.push({name:'Desert Rats projected SP starts',why:`${baseline.projectedStarts} → ${current.projectedStarts} / ${GS_CAP} cap.`});return changes;}
