import {env} from 'cloudflare:workers';
import {buildOffice,changesSince,playerEvidence} from '../../shared/office-engine';
import {dates} from '../../shared/longball';
const bucket=()=> (env as any).REPORTS;
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function read(key:string){const item=await bucket()?.get(key);return item?item.json():null;}
export async function GET(request:Request){try{const url=new URL(request.url);const query=url.searchParams.get('search');
 if(query){if(query.trim().length<2)return response({players:[]});const r=await fetch(`https://statsapi.mlb.com/api/v1/people/search?names=${encodeURIComponent(query.slice(0,80))}&sportIds=1&hydrate=currentTeam`,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error();const json:any=await r.json();return response({players:(json.people??[]).slice(0,15).map((p:any)=>({id:p.id,name:p.fullName,position:p.primaryPosition?.abbreviation,team:p.currentTeam?.name}))});}
 const ids=url.searchParams.get('players');if(ids){const list=ids.split(',');if(list.length<2||list.length>4||list.some(id=>!/^\d+$/.test(id))||new Set(list).size!==list.length)return response({error:'Choose two to four unique MLB players.'},400);const r=await fetch(`https://statsapi.mlb.com/api/v1/people?personIds=${list.join(',')}&hydrate=currentTeam`,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error();const json:any=await r.json();return response({players:await Promise.all((json.people??[]).map((p:any)=>playerEvidence(p)))});}
 const d=dates();let current=await read('daily/current.json');if(!current||current.today!==d.today||Date.now()-Date.parse(current.generatedAt)>15*60000){current=await buildOffice(new Date(),await read('evidence/fantrax.json'));if(bucket())await bucket().put('daily/current.json',JSON.stringify(current));}const baseline=await read(`weeks/${d.monday}.json`);return response({current,baseline,changes:current.feed.status==='current'&&current.scheduleVerified?changesSince(baseline,current):[],changesVerified:current.feed.status==='current'&&current.scheduleVerified,storage:!!bucket()});
 }catch{return response({error:'The front-office evidence service is unavailable. The saved Monday baseline has not been changed.'},503);}}
export async function POST(request:Request){const origin=request.headers.get('Origin');if(origin&&origin!==new URL(request.url).origin)return response({error:'Origin not allowed'},403);try{if(!bucket())return response({error:'Weekly storage is not configured.'},503);const d=dates();const hour=Number(new Intl.DateTimeFormat('en-US',{timeZone:'America/Phoenix',hour:'2-digit',hourCycle:'h23'}).format(new Date()));const key=`weeks/${d.monday}.json`;let baseline=await read(key);const current=await buildOffice(new Date(),await read('evidence/fantrax.json'));await bucket().put('daily/current.json',JSON.stringify(current));let message='Daily evidence refreshed; Monday baseline unchanged.';if(d.day===1&&hour>=7&&!baseline){if(current.feed.status!=='current'||!current.roster.length||!current.scheduleVerified)return response({error:'Monday baseline was not frozen: current Fantrax roster and MLB schedule are required.',current},409);const saved=await bucket().put(key,JSON.stringify({...current,baselineKind:hour<12?'Monday morning baseline':'Monday late capture · not the morning baseline'}),{onlyIf:{etagDoesNotMatch:'*'}});baseline=await read(key);message=saved?'Monday baseline saved and frozen until next Monday.':'Existing Monday baseline preserved.';}return response({message,baselineGeneratedAt:baseline?.generatedAt??null,dailyGeneratedAt:current.generatedAt,week:d.monday});}catch{return response({error:'Refresh failed. Existing baseline is preserved.'},503);}}

